### ISSUE TITLE
Changing core functions to OOPS class and static methods

### ISSUE THREAD

**Issue by aaraamuthan** [arclix/core#12]
### Description

As the functionalities will grow over time, making different files for each feature and maintaining it is difficult. So batching them into a class that handles the required parts can be beneficial for maintaining the code

### Suggested solution

- changing create helper functions into a single generate component Class which contains static functions for each helper module

### Validations

- [X] Follow our [Code of Conduct](https://github.com/arclix/core/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/arclix/core/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://arclix.github.io/arclix-docs/docs/intro).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jitiendran** [comment]
[Triaged] Good to add the feature.
