### ISSUE TITLE
Add pipelines to project for automated testing and deployment

### ISSUE THREAD

**Issue by surya71** [arclix/core#54]
### Description

As a member of the development team, I am proposing to add pipelines to our **_Arclix_** project to automate the testing and deployment processes. This will improve our development workflow and make it easier for us to maintain the project.

The proposed pipelines will include a continuous integration (CI) pipeline to automatically build and test the code whenever changes are pushed to the repository. Additionally, a continuous delivery (CD) pipeline will be implemented to automatically publish the tested code to registries.

This will help to catch errors and bugs earlier in the development process and ensure that the code being deployed is always tested and ready for production. It will also make it easier for new contributors to get started with the project as they can rely on the pipelines to provide feedback on their changes.

### Suggested solution

- Create a new file named `ci.yml` in the .`github/workflows` directory of the Arclix repository.
- Define the pipeline stages in the `ci.yml` file. This should include stages for building, testing, and deploying the code.
- Use the appropriate GitHub Actions for each stage of the pipeline.
- Create scripts for building and testing the code, and include these scripts in the pipeline.
- Use the deploy action to deploy the code to the appropriate environment.
- Test the pipeline locally to ensure that it is working as expected.
- Push the `ci.yml` file to the repository.
- Set up notifications to alert the development team when the pipeline fails. This can be done using email notifications, Slack notifications, or other methods.
- Monitor and maintain the pipeline over time to ensure that it continues to function properly.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/arclix/core/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/arclix/core/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://arclix.github.io/arclix-docs/docs/intro).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jitiendran** [comment]
[ Triaged ] Good to start the development 👍🏻
