### ISSUE TITLE
fix the add index bug for --flat option

### ISSUE THREAD

**Issue by surya71** [arclix/core#71]
### Describe the bug

When I tried to create a component using the `flat` and `addIndex` options, I expected the component to be exported in an index file. However, it was exported in a folder with the component name, which should not have been created as I used the `flat` option.

### Reproduction

https://github.com/arclix/core

### Steps to reproduce

`npx arclix component-name --flat --addIndex`

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
    Memory: 2.70 GB / 7.68 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 9.6.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Brave Browser: 99.1.36.116
    Chrome: 99.0.4844.74
    Firefox: 112.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/arclix/core/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/arclix/core/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://arclix.github.io/arclix-docs/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/arclix/core/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Arclix issue and not a React specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/arclix/core/discussions).
- [X] Please follow [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug and Refer the [example issue](https://github.com/arclix/core/issues/4)

**Comment by jitiendran** [comment]
[ Triaged ] Good to start the development 👍🏻
